---
title: "EDA"
author: "Connor Birkhold"
date: "1/6/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.width = 8, fig.height = 5)
```

```{r include=FALSE}
library(data.table)
library(tidyverse)
```

#### Download the data
```{r}
url <- "https://data.sfgov.org/resource/wg3w-h783.csv"

sfCrime <- fread(url, encoding = 'UTF-8')

str(sfCrime)
```

#### Identify missing values
```{r}
# If there are blank values convert them to NAs
sfCrime[sfCrime == "", ] <- NA

# Calculate the percentage of NAs by column
pct.NA <- function(x){
    sum(is.na(x))/length(x) * 100
}

pctMissVal <- as.data.frame(lapply(sfCrime, pct.NA))
pctMissVal <- gather(pctMissVal, key = 'c_name', value = 'pct_na') %>% 
    arrange(desc(pct_na))

# List columns with percentage of NAs from greatest to least
print(pctMissVal[1:10, ])
```

#### With a high percentage of NAs I want to know more about What makes up the @computed_region columns? Are they useful? Are they candidates for imputation?
```{r results='hide'}
# Let's look into a @computed_region column with less NAs
table(sfCrime$`:@computed_region_qgnn_b9vv`)

# Maybe it is a coding for the district or neighborhood?
table(sfCrime$`:@computed_region_qgnn_b9vv`, sfCrime$police_district)
table(sfCrime$`:@computed_region_qgnn_b9vv`, sfCrime$analysis_neighborhood)

# Not sure of their significance at this point in time. Removing all @computed_region columns because large amount of NAs and don't think they are significant
colNm <- grep("@computed_region", names(sfCrime), value = TRUE)
sfCrime <- sfCrime[, !colNm, with = FALSE]
```

#### What are my percentage of NAs by column with @computed_region removed?
```{r}
# the "@" was converted to "X.." in pctMissVal so running grep again
rowNm <- grep("X..computed_region", pctMissVal$c_name, value = TRUE)

'%ni%' <- Negate("%in%") # creat not in function

pctMissVal <- pctMissVal %>% filter(c_name %ni% rowNm)

print(pctMissVal[1:10,])
```

#### Removing columns filed_online and cad_number due to high percentage of NAs
```{r}
sfCrime <- sfCrime[, -c('filed_online',
                        'cad_number')]
```

