---
title: "EDA_2"
author: "Connor Birkhold"
date: "1/25/2020"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(fig.width = 8, fig.height = 5)
```

```{r include=FALSE}
rm(list = ls())

library(data.table)
library(tidyverse)
library(lubridate)
library(RSQLite)
library(DBI)
library(caret)
```


```{r}
dbPath <- "C:/Users/Cbirkho/Documents/SF_Crime_App/SF_Application/sf_crime_db.sqlite"

db <- dbConnect(SQLite(), dbname = dbPath)

df <- dbGetQuery(db,  "SELECT *
                       FROM incident_reports;")

dbDisconnect(db)

setDT(df)

```

```{r}
df <- df[, type := ifelse(vehicle_flag == 1, 'vehicle',
                          ifelse(weapon_flag == 1, 'weapon', 'other'))]

# Convert the character columns to factors
convStr <- function(x){
  for(i in length(x)){
    catVar <- select_if(x, is.character)
    catVar <- lapply(catVar, as.factor)
    catVar <- as.data.frame(catVar)
    
    numVar <- select_if(x, is.numeric)
    numVar <- lapply(numVar, as.numeric)
    numVar <- as.data.frame(numVar)
    
    final <- cbind(catVar, numVar)
    return(final)
  }
}

df <- convStr(df)

```

```{r}
set.seed(54321)
indexes <- createDataPartition(df$type,
                               times = 1,
                               p = 0.7,
                               list = FALSE)

training <- df[indexes,]
testing <- df[- indexes,]

```

```{r}
# Use 10 fold cross validation (trainControl)
# In short, build 10 models and evaluate how good they are on the data
# Repeat it 3 times (30 models)
# Complete a grid search
train.control <- trainControl(method = "repeatedcv",
                              number = 10,
                              repeats = 3,
                              search = "grid")


# Train the model using 10 fold cross validation repeated 3 times
caret.cv <- train(type ~ incident_day_of_week + police_district + incident_category ,
                  data = training,
                  method = "xgbTree",
                  trControl = train.control)

```


```{r}
caret.cv
```

```{r}
prd <- predict(caret.cv, testing)

confusionMatrix(prd, testing$type)
```

