---
title: "San Francisco Crime App"
author: "Connor Birkhold"
date: "9/23/2019"
output: ioslides_presentation
---

## Overview

We have developed an RStudio Shiny application to help you be prepared for criminal activity in San Francisco. The application does the following:

- Provides a map of criminal activity based on the user inputs
- Provides a prediction of the next type of criminal activity based on the user inputs

The app is hosted at:  https://cmbirkho.shinyapps.io/SF_Crime_App/

## Application Widgets

The application uses the following widgets:

- two instances of a selectInput
    - A field to enter the district of San Francisco the user is interested in
    - A field to enter the month the user is interested in
- submitButton

## Operations Inside the App

- Downloads San Francisco crime data that is updated daily (data located [here](https://data.sfgov.org/Public-Safety/Police-Department-Incident-Reports-2018-to-Present/wg3w-h783))
- Renders an interactive leaflet plot based on the user inputs
- Uses a decision tree to provide a prediction about the next type of crime in the district and month the user has selected
- If there is not data available to render the map or make a prediction notifications on the user interface are displayed

## Example of Leaflet Plot
```{r echo=FALSE, message=FALSE, warning=FALSE}
library(leaflet)
library(tidyverse)
library(lubridate)

url <- "https://data.sfgov.org/resource/wg3w-h783.csv"
sfCrime <- read.csv(url, encoding = 'UTF-8') %>% 
    mutate(cnt = 1,
           incident_date = str_sub(incident_date, 1, 10)) %>%
    mutate(incident_date = ymd(incident_date)) %>% 
    mutate(month = month(incident_date, label = TRUE, abbr = FALSE)) %>% 
    filter(police_district == "Tenderloin") %>% 
    group_by(latitude, longitude, police_district, 
             incident_category, month) %>% 
    summarise(cnt = sum(cnt))

sfCrime <- na.omit(sfCrime)

pal <- colorFactor(topo.colors(11), sfCrime$police_district)

sfCrime %>% 
    leaflet() %>% 
    addTiles() %>% 
    addCircles(weight = 12, 
               radius = sqrt(sfCrime$cnt) * 30,
               color = ~ pal(police_district),
               popup = ~ incident_category) %>% 
    addMarkers(clusterOptions = markerClusterOptions())
```

